# Generated by Django 3.2.8 on 2021-11-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.CharField(max_length=255, null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=122, null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=255, null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=255, null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.IntegerField(null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='registration',
            name='pin',
            field=models.CharField(max_length=122, null='false'),
            preserve_default='false',
        ),
    ]
