# Generated by Django 3.2.8 on 2021-11-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examapp', '0002_auto_20211123_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=12, null='false'),
        ),
    ]
