# Generated by Django 3.2.8 on 2021-11-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examapp', '0005_auto_20211124_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qid',
            field=models.CharField(max_length=255, null='false'),
            preserve_default='false',
        ),
    ]
